version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies for search-photo..."
      - cd Lambda/search-photo
      - pip install -r requirements.txt -t lib
      - cd ..
      - echo "Installing dependencies for index-photo..."
      - cd index-photo
      - pip install -r requirements.txt -t lib
      - cd ..
  build:
    commands:
      - echo "Zipping deployment package for search-photo..."
      - cd search-photo/lib
      - echo "currently in" + `pwd`
      - zip -r9 ../deployment_package_search_photo.zip .
      - cd ..
      - zip -g deployment_package_search_photo.zip lambda_function.py
      - cd ..
      - echo "Zipping deployment package for index-photo..."
      - cd index-photo/lib
      - echo "currently in" + `pwd`
      - zip -r9 ../deployment_package_index_photo.zip .
      - cd ..
      - zip -g deployment_package_index_photo.zip lambda_function.py
      - cd ..
  post_build:
    commands:
      - echo "Updating lambda Function search-photo..."
      - echo "currently in" + `pwd`
      - aws lambda update-function-code --function-name	search-photo --zip-file fileb://search-photo/deployment_package_search_photo.zip
      - echo "Successfully uploaded deployment_package_search_photo.zip"
      - aws lambda update-function-code --function-name	index-photos --zip-file fileb://index-photo/deployment_package_index_photo.zip
      - echo "Successfully uploaded deployment_package_index_photo.zip"

      